services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fixed-float-bidirectional-converter
    command: sleep infinity
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - 0.0.0.0:4175:4173
      - 0.0.0.0:5175:5173
    volumes:
      - ..:/home/node/workspace
      - ~/.gnupg:/home/node/.gnupg
    environment:
      - GPG_TTY=/dev/pts/0
